### Ark-Minting happy path
POST http://127.0.0.1:8000/mint
Content-Type: application/json
Authorization: Bearer 2207a3ab-b01c-44b3-bffd-f1d6bcac4220

{
	"naan": 12345,
	"shoulder": "/s2",
	"url": "https://archive.org/details/random-avdempsey-memories",
	"metadata": {},
	"maintenance_commitment": {}
}

### Ark-minting bad authorization
POST http://127.0.0.1:8000/mint
Content-Type: application/json
Authorization: Bearer DECAFBAD

{
"naan": 12345,
"shoulder": "/t",
"url": "https://archive.org/details/random-avdempsey-memories",
"metadata": {},
"maintenance_commitment": {}
}

### Ark-Updating happy path
PUT http://127.0.0.1:8000/update
Content-Type: application/json
Authorization: Bearer bcaf460b-2070-4fc6-9173-723ca321cdce

{
  "ark": "ark:/13960/tqggqj8jf",
  "url": "https://archive.org/details/random-avdempsey-memories",
  "metadata": "here is some metadata",
  "maintenance_commitment": {}
}
