services:
  postgres:
    container_name: arklet_db
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: arklet
      POSTGRES_PASSWORD: arklet
      POSTGRES_DB: arklet
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres:
