[tox]
env_list =
    py{310,311,312}-django42
    py{310,311,312,313,314}-django52
minversion = 4.23.2

[testenv]
description = run the tests with pytest
package = wheel
wheel_build_env = .pkg
deps =
    django42: Django>=4.2,<4.3
    django52: Django>=5.2,<6
    pytest>=6
    pytest-django
    sentry-sdk
    psycopg[binary]
commands =
    pytest {tty:--color=yes} {posargs}
