# Generated by Django 4.0.10 on 2024-11-11 07:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ark", "0004_apikey_apikey_unique_key_name_for_naan"),
    ]

    operations = [
        migrations.AddField(
            model_name="ark",
            name="created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ark",
            name="updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="ark",
            index=models.Index(
                fields=["created_at"], name="ark_ark_created_e8105b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ark",
            index=models.Index(
                fields=["updated_at"], name="ark_ark_updated_e2654b_idx"
            ),
        ),
    ]
