# Generated by Django 4.0.10 on 2024-11-11 07:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ark", "0005_ark_created_at_ark_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ark",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="ark",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
